### PR TITLE
Erased hardcoded paths for unix based systems. 

### PR DESCRIPTION
**Pull request by alimovlex**
Hello!
Unfortunately, I saw hardcoded paths in your project, so I decided to make system determine the location of adb executable with which POSIX shell command.
As I am not the typescript programmer, you could also offer better solution to this.

Thank you!

### CODE REVIEW

**Comment by AnthonyGress** [comment]
Hey there @alimovlex! I see what you're saying here, but those paths are hardcoded because it should be the static location when the app is installed. Did you have an issue with the file locations when the app was installed, if so, what OS are you using?

I may add an `isDevelopment` flag for running locally and use the paths you suggested.

**Comment by alimovlex** [comment]
> Hey there @alimovlex! I see what you're saying here, but those paths are hardcoded because it should be the static location when the app is installed. Did you have an issue with the file locations when the app was installed, if so, what OS are you using?
> 
> I may add an `isDevelopment` flag for running locally and use the paths you suggested.

I saw @AnthonyGress that you merged this pull request. By the way, I use arch linux with its LTS kernel. Unfortunately, yes, I had some troubles with ADB paths. I launched your app using electron25 but the paths were hardcoded, so your toolkit showed me error. Frankly, I am not the proponent of the path hardcoding, especially at UNIX based systems where the homepath depends on user's login. Therefore, I adjusted the configuration file and it suddenly, worked.

Thank you for accepting and considering my changes!

**Comment by AnthonyGress** [comment]
Out of curiosity @alimovlex  did you install the app via the terminal as outlined in the readme or did you clone the repo and run it locally?

**Comment by alimovlex** [comment]
> Out of curiosity @alimovlex did you install the app via the terminal as outlined in the readme or did you clone the repo and run it locally?

@AnthonyGress I cloned the repo and ran it locally because I am not the proponent of AppImages but it's a universal way of app distribution among all linux distros.

**Comment by AnthonyGress** [comment]
> > Out of curiosity @alimovlex did you install the app via the terminal as outlined in the readme or did you clone the repo and run it locally?
> 
> 
> 
> @AnthonyGress I cloned the repo and ran it locally because I am not the proponent of AppImages but it's a universal way of app distribution among all linux distros.

Gotcha, that's why the paths didn't line up. Should be solved now. All the best

**Comment by alimovlex** [comment]
> > > Out of curiosity @alimovlex did you install the app via the terminal as outlined in the readme or did you clone the repo and run it locally?
> > 
> > 
> > @AnthonyGress I cloned the repo and ran it locally because I am not the proponent of AppImages but it's a universal way of app distribution among all linux distros.
> 
> Gotcha, that's why the paths didn't line up. Should be solved now. All the best

All the best to you too!

**Pull request closed without merging**
